# Site settings
title: Leigh's blog
tagline: eat, play, love
email: 1053696417@qq.com
description: >
  Hi, my name is Nicole li. I'm striving to become a front-end developer.
baseurl: "/ideal-waddle" 
url: "" # the base hostname & protocol for your site
logourl: /assets/images/logo.png 
author: "Nicole li"
author_thumbnail: "/assets/images/avatar.jpg" 
# Theme customization
theme:
  # 主题色
  highlight_color: "#0374C6" #205081 #272935 #6fa873
  # Social media links
  social: 
    github: leighcc

  # Enable share buttons on post footer
  show_share_buttons: 

  # Show author picure, name and social links on post footer
  show_author_info: 

  # Disqus comments manager - shortname
  disqus_shortname: leighccgithubioidealwaddle

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Markdown文件解析器
markdown: kramdown

# 摘要分隔符
excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty

# 分页
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed

gems:
  - jekyll-paginate
  - jemoji